### ISSUE TITLE
Bug en select múltiple

### ISSUE THREAD

**Issue by kroce** [andes/plex#14]
Al seleccionar un item, hay que clickear fuera del select para que se cierre el desplegable.

**Comment by andrrrl** [comment]
Qué contrariedad. Mañana viernes lo reviso!

**Comment by andrrrl** [comment]
Buenas @kroce! analizamos el tema entre todos, y lo que vemos es que:

- El select múltiple no puede saber cuándo se seleccionó el último item, por tanto no sabe cuándo cerrarse.
- Si lo que necesitás es que se seleccione 1 item y se cierre, el componente select tiene una opción para indicar que sea múltiple o no.
- Hay distintos ejemplos en la demo de Plex, contame si ninguno de esos te sirve, y en todo caso explicame un caso de uso para entenderlo mejor.

**Comment by kroce** [comment]
Buenas @andrrrl! Creo que el título estuvo errado, no sería un bug sino mas bien una cuestión de preferencias. Fue una sugerencia de testing, como que resultaría incómodo tener que hacer click para terminar con la selección. 
En este link hay ejemplos de selects múltiples que se cierran con cada selección: http://alxlit.name/bootstrap-chosen/
Igual habría que ver que opina el resto, capaz que lo prefieren así como está.

**Comment by jfgabriel** [comment]
plex-select es un adaptador de selectize. Este plugin tiene una opción de auto-cerrarse. Quizás podríamos dejarlo en false por default, a menos que se quiera la contrario. Habría que implementar una propiedad @Input.
Ver opción closeAfterSelect en [https://github.com/selectize/selectize.js/blob/master/docs/usage.md](https://github.com/selectize/selectize.js/blob/master/docs/usage.md)

**Comment by sychus** [comment]
Hola! agregue la opción para que el plugin cierre luego de seleccionar un valor del plex múltiple. Directamente al componente le agregan la opción [closeAfterSelect]=true que termina siendo un booleando que ingresa al componente en un imput y setea en el plugin la opción de auto-cerrarse luego de seleccionar un elemento. Ver en la lib la propiedad closeAfterSelect.

Pruebenlo a ver que les parece! :-)
