### ISSUE TITLE
Items del dropdown desde función

### ISSUE THREAD

**Issue by manouman** [andes/plex#21]
Necesito generar las opciones que se van a ejecutar en un dropdown dentro de un loop, y que cada elemento tenga la misma acción definida pero con un parametro enviado distinto.
Al parecer por algún motivo pierdo el vínculo hacia la acción, puede ser un bug o bien un capa mil.

¿Que estoy haciendo?

<plex-dropdown label="..." [items]="asignarItems(problema)"></plex-dropdown>

Componente:

asignarItems(problema) {
    let _items ;

    _items = [
        new MenuItem({ label: 'Evolucionar Problema', handler: () => { this.evolucionarProblema(problema) } }),
        new MenuItem({ label: 'Transformar Problema', handler: (() => { this.transformarProblema(problema) }) }),
        new MenuItem({ label: 'Enmendar Problema', handler: (() => { this.enmendarProblema(problema) }) }),
        new MenuItem({ label: 'Ver Detalles', handler: (() => { this.verDetalles(problema) }) }),
        new MenuItem({ label: 'Item con handler', icon: 'wrench', handler: (() => { alert('Funciona!'); return false; }) })
    ];

    return _items;
}

**Comment by andrrrl** [comment]
Si no entiendo mal, si loopeás algo así:

let i = 0;
_items = [ new MenuItem({ label: 'Item con handler', icon: 'wrench', handler: (() => { alert('Funciona ' + i + '!')];
i++;
return items;

No te alerta cada uno "Funciona 0!", "Funciona 1!", etc.
Si es el caso, contame qué rayos hace cuando clickeas, y cómo está el loop.

**Comment by manouman** [comment]
El loop es un simple for en el html.
No me "alerta" nada cuando clickeo un elemento. Probá lo que te digo de utilizar una función para asignar los items al dropdown, dejá unicamente el alert como handler sin hacer nada rebuscado. Para ver esto que te digo no necesitas ni meterlo en un loop.

**Comment by jfgabriel** [comment]
@manouman ¿Esto sigue siendo necesario?
