### ISSUE TITLE
Change en plex-text

### ISSUE THREAD

**Issue by silviroa** [andes/plex#23]
EL evento change se ejecuta cuando se agrega un carácter y también cuando se cambia el foco. Esto provoca que al momento de realizar la siguiente acción se deba esperar la ejecución del change. Ej: en la búsqueda del paciente, al seleccionar uno de la lista, la primera vez se debe hacer un doble click en el botón de selección o el botón de nuevo paciente.

**Comment by jfgabriel** [comment]
Solucionado
