### ISSUE TITLE
plex-accordion

### ISSUE THREAD

**Issue by kroce** [andes/plex#25]
Estaría bueno que se pueda setear si el accordion está desplegado o no x default.

**Comment by andrrrl** [comment]
Queda propiamente registrado el issue reportado, en la máquina de escribir invisible.

**Comment by andrrrl** [comment]
Listo, ya se puede poner un atributo active="true" en cada <plex-panel>, que por defecto está en false (todos los paneles cerrados). Y ahora usa bootstrap 4!
Queda a la espera a ser publicado en NPM.
