### ISSUE TITLE
Options de plex-select quedan ocultas en plex-box

### ISSUE THREAD

**Issue by manouman** [andes/plex#26]
Adjunto imagen para demostrar lo que sucede. Estaría bueno que el plex-select se abra -por encima- del plex-box y evitar ese comportamiento y otro (tercero) scrolling más

![image](https://cloud.githubusercontent.com/assets/1309557/24859409/cd6c63f4-1dc6-11e7-86eb-9a1cd8fcba4e.png)

**Comment by andrrrl** [comment]
Estaría re bueno

**Comment by andrrrl** [comment]
Un quickfix es forzarle a la class de CSS `.plex-box-content ` el valor `overflow: visible; `
El fix queda pendiente de revisión porque podría afectar a toda la estructura.
