### ISSUE TITLE
plex-select - $order

### ISSUE THREAD

**Issue by Llambertucci** [andes/plex#27]
Buenas,

Estamos teniendo un comportamiento erróneo al cargar un arreglo en plex select, le agrega un elemento $order a cada elemento de la lista, lo cual al intentar realizar un update en la base de datos da el siguiente error:

Invalid atomic update value for $order...

El comportamiento esperado es que No se debería agregar ninguna propiedad extra al documento.

Gracias,

Saludos.

**Comment by andrrrl** [comment]
Es un issue harto conocido, de momento el quickfix es hacer `delete miObjeto.$order` antes de enviar a la API. Lo dejo anotado para alguien más que se tope con el problema.
