### ISSUE TITLE
'setContents' of undefined

### ISSUE THREAD

**Issue by fersastre** [andes/plex#50]
Error en consola cuando usamos el Rich Text .

 <plex-text label="Escriba el informe" [(ngModel)]="registro.valor" name="informes" [html]="true" [readonly]="false">
    </plex-text>

![setcontent](https://user-images.githubusercontent.com/11932731/42278346-e510cd44-7f70-11e8-817b-cb60053a455b.png)

**Comment by liquid36** [comment]
@fersastre Debido al dinamismo de RUP, el coponente que renderiza el ritch componente no llegaba a ser inicializado. Se corrigió el problema en la última públicación.
