### ISSUE TITLE
Tamaño del textarea del rich text

### ISSUE THREAD

**Issue by fersastre** [andes/plex#51]
El tamaño del textarea del rich text es muy grande para la ejecución de RUP. Quizás podríamos pasar el tamaño por parámetro para los diferentes componentes! 

![issueplex](https://user-images.githubusercontent.com/11932731/42278423-26ce5a8a-7f71-11e8-8cd5-4fed27ba3b53.png)

**Comment by jfgabriel** [comment]
Ya está solucionad en la última versión de Plex
