### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by negro89** [andes/plex#66]
**Comportamiento actual:** Al ejecutar un componente en cuyo template el no se haya declarado header, se dibuja la linea separadora. 

**Comportamiento esperado:** Si no se declara header, la linea no debería dibujarse.

![pantallazo-2018-11-06 11-56-46](https://user-images.githubusercontent.com/37875706/48073039-997ce300-e1bc-11e8-9591-9aa0e4be3fe2.png)

**Comment by liquid36** [comment]
@negro89  Qué versión de plex estas usando? El último plex cambio la estructura interna del plex-layout-sidebar. Se te debería ver bien.
