### ISSUE TITLE
PLEX-DATE: Fecha incompleta/invalida

### ISSUE THREAD

**Issue by plammel** [andes/plex#82]
### Comportamiento actual
Al ingresar la fecha por teclado en el input, plex-date actualiza el valor del atributo bindeado con una fecha autocompletada como se ejemplifica a continuación: 
- Si ingreso 2 --> 02/MesCorriente/AñoCorriente
- Si ingreso 22 --> 22/MesCorriente/AñoCorriente
- Si ingreso 222 --> 22/02/AñoCorriente
etc.

De similiar manera, si, por ejemplo, quiero cambiar de año manualmente, ocurre lo siguiente:
- fecha actual por defecto: 28/05/2019
- borro último digito del año: 28/05/201 --> 28/05/0201 
- agrego nuevo dígito del año: 28/05/2018 --> 28/05/2018 

Este comportamiento afecta en los casos en que en la app dispara la búsqueda en el evento de cambio, sobretodo en el último caso descrito, cuando se busca por fecha de inicio, disparando primero la búsqueda con valor de fecha 28/05/0201 y después 28/05/2018. Siendo la primera búsqueda por un rango de fecha más grande (año de inicio 201) que la segunda, esta consulta es la última en resolverse, produciendo un resultado de búsqueda fuera de rango.

### Resultado esperado 
Plex-select debería:
a) Validar que la fecha está completa antes de actualizar el valor al atributo bindeado en el componente.
ó b) Poder ser configurable si autocompleta fechas o no.
### Pasos para reproducir el problema 

[![Watch the video](https://user-images.githubusercontent.com/25707055/58556018-5c784c80-81f1-11e9-9614-0d018bcfae31.png)](https://www.loom.com/share/a0446da77a0c4a18af7c705c95659fa2)

**Comment by liquid36** [comment]
@plammel Vos lo que necesitas ahí es cancelar el request anterior cuando cambia el valor de la fecha.

Ejemplo:
 https://github.com/andes/app/blob/3a812bf6d1141ecb052f2de9cd38cbfc90203e19/src/app/components/snomed/snomed-buscar.component.ts#L50

**Comment by plammel** [comment]
Genial @liquid36!! :ok_hand:
Mirá @lucasgonzalezm
